module.exports = {
  '-10': 'like suicide is the only option',
  '-9' : 'Terrible',
  '-8' : 'OH GOD WHY',
  '-7' : 'Snow day',
  '-6' : 'Very, very bad',
  '-5' : 'Very Bad',
  '-4' : 'Bad',
  '-3' : 'Not Good',
  '-2' : 'Not Great',
  '-1' : 'Meh',
  '0'  : 'Average',
  '1'  : 'Alright',
  '2'  : 'Not Bad',
  '3'  : 'Sweet',
  '4'  : 'Good',
  '5'  : 'Great',
  '6'  : 'Awesome',
  '7'  : 'Incredible',
  '8'  : 'Ecstatic',
  '9'  : 'Like a boss',
  '10' : 'Nirvana'
}